apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-viib
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iaxb-tenant/status-quarkus-io/statusquarkusio-viib@sha256:fbdf53038ceaa6ef48347bc31c28c649a44a6100f680f030e9540d900778016a
        name: my-java-quarkus
        resources: {}
status: {}
